/** Short, original editorial lines for the public page heroes. */
export const heroQuotes: Record<string, string> = {
  '/about': 'People help us grow.',
  '/about/faculty': 'Guidance makes room to grow.',
  '/about/management': 'People give purpose its shape.',
  '/about/mission-vision': 'Purpose guides every step.',
  '/admissions': 'The next chapter starts here.',
  '/blog': 'Ideas are worth sharing.',
  '/blog/alumni-success-stories': 'See where their journeys led.',
  '/blog/bba-admission-in-vijayawada': 'Begin with a business direction.',
  '/blog/bba-admission-vijayawada-best-bba-colleges': 'Choose your business beginning.',
  '/blog/best-college-to-study-in-vijayawada-and-andhra-pradesh': 'Find a place to thrive.',
  '/blog/best-colleges-in-vijayawada-andhra-pradesh-for-hotel-management-business-management-intermediat': 'Many paths start in Vijayawada.',
  '/blog/best-colleges-in-vijayawada-andhra-pradesh-for-hotel-management-business-management-intermediat-1': 'A good choice opens possibilities.',
  '/blog/best-jr-college-in-andhra-pradesh-a-complete-guide-for-students-in-2026': 'Build a strong next step.',
  '/blog/build-your-future-with-westin-school-of-business-management-vijayawada': 'Business ideas begin here.',
  '/blog/dhm-course-details-vijayawada-1': 'Explore the hospitality details.',
  '/blog/diploma-hotel-management-vijayawada': 'A practical path into hospitality.',
  '/blog/find-the-best-bba-college-in-vijayawada-and-andhra-pradesh-a-simple-student-guide': 'Find the BBA that fits.',
  '/blog/hospitality-story': 'Service starts with people.',
  '/blog/hotel-management-colleges-in-andhra-pradesh': 'Look closer at hospitality study.',
  '/blog/hotel-management-colleges-in-vijayawada-a-complete-guide': 'Make sense of your options.',
  '/blog/hotel-management-colleges-in-vijayawada-fees': 'Understand the cost of study.',
  '/blog/hotel-management-course-vijayawada': 'Let your hospitality journey begin.',
  '/blog/mec-cec-junior-college-vijayawada': 'Choose the foundation for you.',
  '/blog/mec-guide': 'Know your MEC and CEC options.',
  '/blog/the-best-college-for-hotel-management-placement': 'Look beyond the classroom.',
  '/blog/top-10-hotel-management-colleges-in-vijayawada': 'Compare paths with confidence.',
  '/blog/top-bba-colleges-in-vijayawada': 'Explore business study nearby.',
  '/blog/westin-college-of-hotel-and-business-management-the-pride-of-vijay': 'Get to know Westin.',
  '/blog/westin-college-of-hotel-management-ug-courses-2025-a-simple-student-guide': 'Find your undergraduate route.',
  '/blog/westin-college-of-hotel-management-vijayawada-the-top-hotel-management-college-in-india': 'Step inside hospitality learning.',
  '/blog/westin-college-of-hotel-management-vijayawada-the-top-hotel-management-college-in-india-1': 'Practice brings hospitality to life.',
  '/blog/westin-school-of-business-management-a-top-bba-college-in-india': 'Business learning has many sides.',
  '/blog/westin-the-best-college-of-business-management-in-andhra-pradesh': 'See business study in context.',
  '/blog/westin-the-best-college-of-business-management-in-vijayawada': 'Discover business learning in Vijayawada.',
  '/blog/westin-the-best-college-of-hotel-management-in-andhra-pradesh': 'Hospitality has room to grow.',
  '/blog/westin-the-best-college-of-hotel-management-in-vijayawada': 'The craft of welcome starts here.',
  '/blog/which-is-the-best-college-in-international-placements': 'Consider where learning can lead.',
  '/blog/which-is-the-best-intermediate-college-in-vijayawada': 'Make your intermediate choice count.',
  '/blog/yuva-tourism-event-2024': 'Tourism brings ideas together.',
  '/campus': 'Belong, learn, grow.',
  '/campus/events': 'Shared moments shape a place.',
  '/campus/events/bhm-diwali-2024': 'Bright moments are better together.',
  '/campus/events/cake-distribution': 'A little kindness goes far.',
  '/campus/events/cake-mixing': 'Good things take care to make.',
  '/campus/events/diwali': 'Celebrate the light we share.',
  '/campus/events/flower-decoration': 'Make room for colour.',
  '/campus/events/ghsdp-2024': 'Skills grow through shared practice.',
  '/campus/events/iftar-party': 'A table brings us together.',
  '/campus/events/independence': 'Celebrate the freedom to grow.',
  '/campus/events/janstami-bhm': 'Tradition makes room for joy.',
  '/campus/events/mr-and-ms': 'Confidence takes the stage.',
  '/campus/events/old-age-home': 'Care connects generations.',
  '/campus/events/onam': 'Come together in colour.',
  '/campus/events/open-house': 'See the place for yourself.',
  '/campus/events/pattabi': 'A college moment to remember.',
  '/campus/events/sankranthi': 'Welcome a season of possibility.',
  '/campus/events/sparkles': 'Let the moment shine.',
  '/campus/events/sparkles-2024': 'Share a little sparkle.',
  '/campus/events/star': 'Every star has a beginning.',
  '/campus/events/tourism': 'Discover what travel connects.',
  '/campus/events/tourism-2024': 'Explore a wider world.',
  '/campus/events/vinayaka-chavithi': 'Traditions bring people close.',
  '/campus/infrastructure': 'Spaces make practice possible.',
  '/career-planner': 'Make a plan for what comes next.',
  '/contact': 'A conversation opens doors.',
  '/gallery': 'See the moments that matter.',
  '/gallery/gallery-freshers': 'New faces, shared beginnings.',
  '/gallery/gallery-learning': 'See learning in motion.',
  '/magazine': 'Every page holds a possibility.',
  '/news': 'Follow the Westin story.',
  '/news/awards': 'Give good work its moment.',
  '/news/business-quiz': 'Curiosity earns the spotlight.',
  '/news/international-hotel-placements-2017-18': 'A step towards wider horizons.',
  '/news/interviews': 'Preparation meets opportunity.',
  '/news/news-more': 'There is more to discover.',
  '/news/westin-students-uae-bahrain': 'New places, new possibilities.',
  '/partners': 'Connections help us go further.',
  '/partners/bineid': 'Industry links open new doors.',
  '/placements': 'Make room for possibility.',
  '/programs': 'Make a path your own.',
  '/programs/bba': 'Ideas grow into action.',
  '/programs/bba-honours': 'Curiosity can take you further.',
  '/programs/bhm-honours': 'Take your craft further.',
  '/programs/bhm-three-year': 'Practice builds confidence.',
  '/programs/dhm-one-year': 'Find your hospitality footing.',
  '/programs/food-production': 'Good food begins with care.',
  '/programs/hotel-management': 'Care becomes a craft.',
  '/programs/intermediate': 'Strong beginnings open paths.',
  '/programs/pgdhm': 'Build on what you know.',
  '/programs/work-integrated-hotel-management': 'Learn where the work happens.',
  '/publishing-house': 'Every story starts somewhere.',
  '/search': 'Find what moves you forward.',
  '/success-stories': 'Every journey has its moment.',
  '/success-stories/indra-kiran': 'An interview can open doors.',
  '/success-stories/sudharshan': 'Mentorship travels with you.',
  '/success-stories/vara-prasad': 'One step can lead far.',
  '/testimonials': 'Hear the people behind the story.',
  '/testimonials/danny-barakat': 'Good partnerships begin with trust.',
  '/testimonials/founder': 'Knowledge grows into character.',
  '/testimonials/michael-wierling': 'The right connection opens a path.',
  '/testimonials/simon-morley': 'Good work connects across cities.',
  '/why-westin': 'Learn with purpose.',
}

export function heroQuoteFor(path: string, title: string) {
  const normalizedPath = path.replace(/\/+$/, '') || '/'
  return heroQuotes[normalizedPath] ?? `A closer look at ${title.replace(/[.!?]+$/, '').trim()}.`
}
